### PR TITLE
Dogfood: 4-21

### PR DESCRIPTION
**Pull request by naterush**
# Description

1. Removed unnecessary print in installer.
2. Focus on search input in file browser once you click on new folder
3. Fixes a massive bug in signup flow where modal was not visible, and buttons were all wacky.

# Testing

Please provide a list of the ways you can "access" or use the functionality. Please try and be exhaustive here, and make sure that you test everything you list.

- [ ] I have tested this on real data that is reasonable and large
- [ ] If I changed the interaction with JupyterLab, I tested that it does not break other programs (like VS Code), and tested that it works "multiple times" in the same notebook.

# Documentation

Note if any new documentation needs to addressed or reviewed.

### CODE REVIEW

**Comment by naterush** [comment]
Oh weird. Is this also the case on JLab? If so, then it seems like it's potentially from the recent dropdown changes we've made to scroll bars. 

Wanna take a shot at fixing them?

**Comment by aarondr77** [comment]
> 

Yeah, let me check if its on Lab too. And I'll also check if its just edge. And then I can try to fix.

**Comment by aarondr77** [comment]
Okay, yeah so I think the lack of scrollbar is a windows thing and the shakyness is just a [windows edge, notebook thing]. 
I'll fix the lack of scrollbar rn.

**Review by naterush — COMMENTED** [review]
Looks good!

**Pull request merged**
