### PR TITLE
7 26 usability

### PR DESCRIPTION
**Pull request by naterush**
# Description

1. Made button to reopen onboarding checklist. This only exists during your first usage... that good?
2. For the bulk of the checklist, made it so it opens the feature. This is sweet. It doesn't do the same for the later links, but I think it's fine. Also, what do for those that aren't active (b/c no imported data?) -- I think it could be fine to just leave and usability test.
3. Make the installer not upgrade the user.json if it shouldn't!

# Testing

Test all these things. You'll have to clear your user.json to pretent to be a first time user.

# Documentation

No.

### CODE REVIEW

**Review by naterush — COMMENTED** [review]
Looks good!

**Comment by naterush** [comment]
There's another "button click doesn't open import here" - but I think we should let it be, and let the AB test for next week fix it up. We could combine these, see my comments in Zulip!

**Comment by aarondr77** [comment]
In the control variant, the `open checklist` button in the top right corner is still there. It disapears when you click on it.

**Comment by aarondr77** [comment]
When I reopen the checklist, it flashes through all of the previous states before moving to the new screen.

https://user-images.githubusercontent.com/18709905/181091869-3db31f0c-314f-4db4-9d98-d474a356a806.mov

**Comment by naterush** [comment]
@aarondr77 flashing is a very hard fix! We'd need to track different state or something -- it's so minor, I think it's not worth it.

**Pull request merged**
