### PR TITLE
mitosheet: save scroll positions in sheets

### PR DESCRIPTION
**Pull request by naterush**
# Description

Saves the scroll positions in sheets. Like every other application every person has ever used.

# Testing

Make sure this works with adding, removing, deleting sheets, etc.

# Documentation

No.

### CODE REVIEW

**Comment by aarondr77** [comment]
1. Import the RockArt 600 column datasets in our large dataset.
2. Duplicate it
3. In the first sheet, scroll over to the right a bunch
4. Delete the first sheet
5. Notice that the second sheet (which is now the first sheet) is scrolled to the same position that the first sheet was in.

**Comment by aarondr77** [comment]
Maybe clear analysis should reset the horizontal scrolls too? It feels more resetty

**Comment by aarondr77** [comment]
Other than that LGTM

**Comment by naterush** [comment]
@aarondr77 just like with width data, because we don't have sheet ids, figuring out the saving of scroll with deleting is fucked. 

The same thing is true with column widths, but I've literally never noticed it before (and if anything this is a less big deal with column widths).

**Comment by naterush** [comment]
Clearning an anlaysis is similarly very hard to fix for very little bang for buck. Can we forget about both of these?

**Comment by aarondr77** [comment]
Yeah. forgot!

**Pull request merged**
