### PR TITLE
Change imports usability fix 2

### PR DESCRIPTION
**Pull request by aarondr77**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context, and the specification if there is one. 

# Testing

Please provide a list of the ways you can "access" or use the functionality. Please try and be exhaustive here, and make sure that you test everything you list.

- [ ] I have tested this on real data that is reasonable and large
- [ ] If I changed the interaction with JupyterLab, I tested that it does not break other programs (like VS Code), and tested that it works "multiple times" in the same notebook.

# Documentation

Note if any new documentation needs to addressed or reviewed.

### CODE REVIEW

**Comment by aarondr77** [comment]
Leaving the taskpane opens up a can of worms:
1. Since the step_ids change, we need to refresh the step import data to get the correct step ids in the `UpdateImportsPostReplayAnalysis`.
2. In the `UpdateImportsPostReplayAnalysis` we have now successfully replayed the analysis, we technically want to be in the post replay analysis state. 

This all gets simplified if we just close the taskpane.

**Comment by naterush** [comment]
Gotcha. This is good complexity that I didn't realize existed that make these proposed changes much harder than they should be!

I think moving this back to the popup makes sense - you should just be able to configure where the popup goes easily perhaps?

For my knowledge, did you know about this complexity on the previous PR? Or is this something that you discovered in trying to make this change.

**Comment by aarondr77** [comment]
I knew about the `UpdateImportsPostReplayAnalysis` one, but then discovered those other two as I did this PR.

**Comment by aarondr77** [comment]
Closed in favor of https://github.com/mito-ds/monorepo/pull/501/files

**Pull request closed without merging**
